module.exports = {
  ERROR_LOCKDOWN_MODE: 'LockDown',
  ERROR_NIL_ARGUMENTS: 'Invalid arguments!',
  ERROR_INVALID_NETWORK_ID: 'Invalid network id',
  ERROR_INVALID_EVENT_NAME: 'Invalid event name',
  ERROR_OPERATION_NOT_QUEUED: 'OperationNotQueued',
  ERROR_OPERATION_ALREADY_QUEUED: 'OperationAlreadyQueued',
  ERROR_OPERATION_ALREADY_CANCELED: 'OperationAlreadyCancelled',
  ERROR_OPERATION_ALREADY_EXECUTED: 'OperationAlreadyExecuted',
  ERROR_UNABLE_TO_GET_GUARDIANS: 'Unable to get the guardians',
  ERROR_CHALLENGE_PERIOD_NOT_TERMINATED: 'ChallengePeriodNotTerminated',
  ERROR_REPLACEMENT_UNDERPRICED: 'replacement transaction underpriced',
  ERROR_TRANSACTION_EXECUTION_REVERTED: 'transaction execution reverted',
  ERROR_INVALID_PROPOSED_TIMESTAMP: 'Invalid proposed timestamp',
  ERROR_INSUFFICIENT_FUNDS: 'insufficient funds',
  ERROR_NETWORK_FEE_NOT_ACCEPTED: 'Insufficient network fee',
  ERROR_NO_ACTORS_PROPAGATED_EVENT_FOUND: 'No actors propagated event found!',
}
