module.exports = {
  KEY_DB: 'db',
  KEY_URL: 'url',
  KEY_NAME: 'name',
  KEY_SIGNATURES: 'signatures',
  KEY_EVENTS: 'events',
  KEY_CONTRACT: 'contract',
  KEY_CHAIN_NAME: 'chain-name',
  KEY_CHAIN_TYPE: 'chain-type',
  KEY_TX_TIMEOUT: 'tx-timeout',
  KEY_NETWORK_ID: 'network-id',
  KEY_IDENTITY_GPG: 'identity',
  KEY_TABLE_EVENTS: 'table-events',
  KEY_PROVIDER_URL: 'provider-url',
  KEY_HUB_ADDRESS: 'hub-address',
  KEY_CHALLENGE_PERIOD: 'challenge-period',
  KEY_LOOP_SLEEP_TIME: 'loop-sleep-time',
  KEY_PROTOCOLS: 'protocols',
  KEY_SUPPORTED_CHAINS: 'supported-chains',
  KEY_TYPE: 'type',
  KEY_DATA: 'data',
}
