module.exports = {
  ERROR_TIMEOUT: 'Timeout',
  ERROR_INVALID_TYPE: 'Invalid type',
  ERROR_UNKNOWN_RETURN: 'Unknown return',
  ERROR_KEY_NOT_FOUND: 'Key not found in object!',
  ERROR_INVALID_OBJECT: 'Object given is invalid',
  ERROR_INVALID_BRIDGE_SIDE: 'Invalid bridge side',
  ERROR_ENCLAVE_CALL_FAILED: 'Enclave call failed',
  ERROR_WRONG_NUMBER_OF_ARGS: 'Wrong number of args',
  ERROR_ENCLAVE_CALL_TIMEOUT: 'Enclave call timeout',
  ERROR_INVALID_RETRYING_MODE: 'Invalid retrying mode',
  ERROR_UNEXPECTED_HTTP_STATUS: 'Unexpected HTTP status',
  ERROR_SLEEP_UNDEFINED_ARG: "Can't sleep: argument is Nil",
  ERROR_SCHEMA_VALIDATION_FAILED: 'Schema validation failed',
  ERROR_WEBSOCKET_REQUEST_TIMEOUT: 'Websocket request expired!',
  ERROR_WEBSOCKET_CONNECTION_FAILURE: 'Failed to connect to Websocket!',
  ERROR_DB_CLIENT: 'Failed connecting to the db client, is it running?',
  ERROR_UNABLE_TO_FIND_PATHS: 'Unable to find the given paths in object',
  ERROR_NO_UPDATE_FOR_REPORT: 'No report was updated for the defined query',
  ERROR_JSON_RESPONSE_EXTRACTION: 'Failed to extract the json from the response:',
  ERROR_INVALID_SYMBOL_FOR_BRIDGE_TYPE: 'Invalid symbol for the given bridge type',
  ERROR_FILE_NOT_EXISTS: 'The specified file does not exist',
  ERROR_GPG_DECRYPTION_FAILED: 'Failed to decrypt file',
  ERROR_FAILED_TO_PARSE_JSON: 'Failed to parse JSON!',
}
