module.exports = {
  SCHEMA_NAME_KEY: 'name',
  SCHEMA_URL_KEY: 'url',
  SCHEMA_TABLE_EVENTS_KEY: 'table-events',
  SCHEMA_PROVIDER_URL_KEY: 'provider-url',
  SCHEMA_CHAIN_ID_KEY: 'chain-id',
  SCHEMA_CHAIN_NAME_KEY: 'chain-name',
  SCHEMA_CHAIN_TYPE_KEY: 'chain-type',
  SCHEMA_EVENTS_KEY: 'events',
  SCHEMA_DB_KEY: 'db',
  SCHEMA_TOKEN_CONTRACTS_KEY: 'token-contracts',
  SCHEMA_ORIGINATING_CHAIN_ID_KEY: 'originatingChainId',
  SCHEMA_ORIGINATING_TRANSACTION_HASH_KEY: 'originatingTransactionHash',
  SCHEMA_AMOUNT_KEY: 'amount',
  SCHEMA_DESTINATION_ADDRESS_KEY: 'destinationAddress',
  SCHEMA_DESTINATION_CHAIN_ID_KEY: 'destinationChainId',
  SCHEMA_USER_DATA_KEY: 'userData',
  SCHEMA_TOKEN_ADDRESS_KEY: 'tokenAddress',
  SCHEMA_EVENT_NAME_KEY: 'eventName',
  SCHEMA_STATUS_KEY: 'status',
}
