const ERROR_ESTIMATE_GAS = 'estimateGas'
const ERROR_CODE_INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS'
const KEY_TX_HASH = 'hash'
const ERROR_REPLACEMENT_UNDERPRICED = 'replacement transaction underpriced'
const TOPIC_HASH = 'topicHash'

module.exports = {
  ERROR_ESTIMATE_GAS,
  ERROR_CODE_INSUFFICIENT_FUNDS,
  KEY_TX_HASH,
  ERROR_REPLACEMENT_UNDERPRICED,
  TOPIC_HASH,
}
